name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: house_it
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ECSE428
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x HouseIt-Backend/gradlew

    - name: Clean and Build
      working-directory: ./HouseIt-Backend
      run: ./gradlew clean build --info
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/house_it
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: ECSE428

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          HouseIt-Backend/build/reports/tests/
          HouseIt-Backend/build/test-results/
          HouseIt-Backend/build/reports/cucumber/
