name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ECSE428
          POSTGRES_DB: testdb

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.10'

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Navigate to Backend Directory
      working-directory: ./HouseIt-Backend
      run: pwd

    - name: Build with Gradle Wrapper
      working-directory: ./HouseIt-Backend
      run: ./gradlew build

    - name: Run Tests
      working-directory: ./HouseIt-Backend
      run: ./gradlew test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: ECSE428
