name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: house_it
          POSTGRES_PASSWORD: ECSE428
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permissions for gradlew
      run: chmod +x ./ECSE-428-Fall-2024/HouseIt-Backend/gradlew

    - name: Execute Gradle build
      working-directory: ./ECSE-428-Fall-2024/HouseIt-Backend
      run: ./gradlew clean build
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/house_it
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: ECSE428
        
